### ISSUE TITLE
^ what means?

### ISSUE THREAD

**Issue by zxy7** [mistlog/typetype#49]
Why do you use ^ before each {}?
What's the meaning

**Comment by mistlog** [comment]
to emphasize that it's not statement, for example: 
```ts
/*
  type conditional = 1 extends string ? "string" : "number"
*/
type conditional = ^{
    if(1 extends string) {
        return "string"
    } else {
        return "number"
    }
}
```

we use statements to denote type, this kind of usage needs new syntax, that's ^{...}, not "use ^ before each {}",
